26. Port xcin to Cygwin.     Thanks to weijr <weijr@magic.b81.org>.
git-svn-id: file:///home/data/repos/svk/depos/xcin/mirror/trunk@131 8f09ba1b-be14-0410-94fe-a50ee1c8db6e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12347,70 +12347,6 @@ CPPFLAGS="$OLD_CPPFLAGS $incs"
 LDFLAGS="$OLD_LDFLAGS $libs"
 
 LIBS="$OLD_LIBS"
-echo "$as_me:$LINENO: checking for setlocale in -lxpg4" >&5
-echo $ECHO_N "checking for setlocale in -lxpg4... $ECHO_C" >&6
-if test "${ac_cv_lib_xpg4_setlocale+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lxpg4  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char setlocale ();
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-setlocale ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_xpg4_setlocale=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_xpg4_setlocale=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_xpg4_setlocale" >&5
-echo "${ECHO_T}$ac_cv_lib_xpg4_setlocale" >&6
-if test $ac_cv_lib_xpg4_setlocale = yes; then
-   with_locale_lib=-lxpg4
-else
-   with_locale_lib=""
-fi
-
-
-
-LIBS="$OLD_LIBS"
 
 for ac_func in dlopen
 do
@@ -13907,6 +13843,76 @@ fi
 
 LDFLAGS="$OLD_LDFLAGS $libs"
 
+LIBS="$OLD_LIBS"
+if test $os_type = CYGWIN; then
+    with_locale_lib="-L$x_libraries -lX11"
+else
+    echo "$as_me:$LINENO: checking for setlocale in -lxpg4" >&5
+echo $ECHO_N "checking for setlocale in -lxpg4... $ECHO_C" >&6
+if test "${ac_cv_lib_xpg4_setlocale+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxpg4  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char setlocale ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+setlocale ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_xpg4_setlocale=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_xpg4_setlocale=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_xpg4_setlocale" >&5
+echo "${ECHO_T}$ac_cv_lib_xpg4_setlocale" >&6
+if test $ac_cv_lib_xpg4_setlocale = yes; then
+   with_locale_lib=-lxpg4
+else
+   with_locale_lib=""
+fi
+
+fi
+
+
+LDFLAGS="$OLD_LDFLAGS $libs"
+
 if test x$without_tabe = x; then
     echo "$as_me:$LINENO: checking tabe data files" >&5
 echo $ECHO_N "checking tabe data files... $ECHO_C" >&6
@@ -15022,11 +15028,11 @@ s,@INSTALL_DATA@,$INSTALL_DATA,;t t
 s,@INSTALL@,$INSTALL,;t t
 s,@PERL@,$PERL,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
-s,@with_locale_lib@,$with_locale_lib,;t t
 s,@with_dl_lib@,$with_dl_lib,;t t
 s,@with_socket_lib@,$with_socket_lib,;t t
 s,@GNU_GETTEXT@,$GNU_GETTEXT,;t t
 s,@OLD_GNU_GETTEXT@,$OLD_GNU_GETTEXT,;t t
+s,@with_locale_lib@,$with_locale_lib,;t t
 s,@tabe_data@,$tabe_data,;t t
 s,@with_extra_inc@,$with_extra_inc,;t t
 s,@with_extra_lib@,$with_extra_lib,;t t
